#ifndef EDITORCOMMANDS_H
#define EDITORCOMMANDS_H

#include "EditorCommands/setlayermask.h"
#include "EditorCommands/setspriteinteraction.h"
#include "EditorCommands/setentranceinteraction.h"
#include "EditorCommands/setpathinteraction.h"
#include "EditorCommands/setlocationinteraction.h"
#include "EditorCommands/raiseobject.h"
#include "EditorCommands/lowerobject.h"
#include "EditorCommands/raiselayer.h"
#include "EditorCommands/lowerlayer.h"
#include "EditorCommands/deletebgdatobject.h"
#include "EditorCommands/deletesprite.h"
#include "EditorCommands/deleteentrance.h"
#include "EditorCommands/deletezone.h"
#include "EditorCommands/deletelocation.h"
#include "EditorCommands/deletepathnode.h"
#include "EditorCommands/deleteprogresspathnode.h"
#include "EditorCommands/insertbgdatobj.h"
#include "EditorCommands/insertsprite.h"
#include "EditorCommands/insertentrance.h"
#include "EditorCommands/insertzone.h"
#include "EditorCommands/insertzonebackground.h"
#include "EditorCommands/insertzonebounding.h"
#include "EditorCommands/insertlocation.h"
#include "EditorCommands/insertpath.h"
#include "EditorCommands/insertpathnode.h"
#include "EditorCommands/insertprogresspath.h"
#include "EditorCommands/insertprogresspathnode.h"
#include "EditorCommands/moveobject.h"
#include "EditorCommands/resizeobject.h"
#include "EditorCommands/increaseobjectposition.h"
#include "EditorCommands/increaseobjectsize.h"

#endif // EDITORCOMMANDS_H
